// Code generated by Stan version 2.15.0

#include <stan/model/model_header.hpp>

namespace gp_predict_analytic_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;

class gp_predict_analytic_model : public prob_grad {
private:
    int N1;
    vector_d x1;
    vector_d y1;
    int N2;
    vector_d x2;
    vector_d mu;
    matrix_d L;
public:
    gp_predict_analytic_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        typedef boost::ecuyer1988 rng_t;
        rng_t base_rng(0);  // 0 seed default
        ctor_body(context__, base_rng, pstream__);
    }

    template <class RNG>
    gp_predict_analytic_model(stan::io::var_context& context__,
        RNG& base_rng__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, base_rng__, pstream__);
    }

    template <class RNG>
    void ctor_body(stan::io::var_context& context__,
                   RNG& base_rng__,
                   std::ostream* pstream__) {
        current_statement_begin__ = -1;

        static const char* function__ = "gp_predict_analytic_model_namespace::gp_predict_analytic_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        context__.validate_dims("data initialization", "N1", "int", context__.to_vec());
        N1 = int(0);
        vals_i__ = context__.vals_i("N1");
        pos__ = 0;
        N1 = vals_i__[pos__++];
        validate_non_negative_index("x1", "N1", N1);
        context__.validate_dims("data initialization", "x1", "vector_d", context__.to_vec(N1));
        validate_non_negative_index("x1", "N1", N1);
        x1 = vector_d(static_cast<Eigen::VectorXd::Index>(N1));
        vals_r__ = context__.vals_r("x1");
        pos__ = 0;
        size_t x1_i_vec_lim__ = N1;
        for (size_t i_vec__ = 0; i_vec__ < x1_i_vec_lim__; ++i_vec__) {
            x1[i_vec__] = vals_r__[pos__++];
        }
        validate_non_negative_index("y1", "N1", N1);
        context__.validate_dims("data initialization", "y1", "vector_d", context__.to_vec(N1));
        validate_non_negative_index("y1", "N1", N1);
        y1 = vector_d(static_cast<Eigen::VectorXd::Index>(N1));
        vals_r__ = context__.vals_r("y1");
        pos__ = 0;
        size_t y1_i_vec_lim__ = N1;
        for (size_t i_vec__ = 0; i_vec__ < y1_i_vec_lim__; ++i_vec__) {
            y1[i_vec__] = vals_r__[pos__++];
        }
        context__.validate_dims("data initialization", "N2", "int", context__.to_vec());
        N2 = int(0);
        vals_i__ = context__.vals_i("N2");
        pos__ = 0;
        N2 = vals_i__[pos__++];
        validate_non_negative_index("x2", "N2", N2);
        context__.validate_dims("data initialization", "x2", "vector_d", context__.to_vec(N2));
        validate_non_negative_index("x2", "N2", N2);
        x2 = vector_d(static_cast<Eigen::VectorXd::Index>(N2));
        vals_r__ = context__.vals_r("x2");
        pos__ = 0;
        size_t x2_i_vec_lim__ = N2;
        for (size_t i_vec__ = 0; i_vec__ < x2_i_vec_lim__; ++i_vec__) {
            x2[i_vec__] = vals_r__[pos__++];
        }

        // validate, data variables
        check_greater_or_equal(function__,"N1",N1,1);
        check_greater_or_equal(function__,"N2",N2,1);
        // initialize data variables
        validate_non_negative_index("mu", "N2", N2);
        mu = vector_d(static_cast<Eigen::VectorXd::Index>(N2));
        stan::math::fill(mu,DUMMY_VAR__);
        validate_non_negative_index("L", "N2", N2);
        validate_non_negative_index("L", "N2", N2);
        L = matrix_d(static_cast<Eigen::VectorXd::Index>(N2),static_cast<Eigen::VectorXd::Index>(N2));
        stan::math::fill(L,DUMMY_VAR__);

        try {
            {
                validate_non_negative_index("Sigma", "N1", N1);
                validate_non_negative_index("Sigma", "N1", N1);
                matrix_d Sigma(static_cast<Eigen::VectorXd::Index>(N1),static_cast<Eigen::VectorXd::Index>(N1));
                (void) Sigma;  // dummy to suppress unused var warning

                stan::math::initialize(Sigma, std::numeric_limits<double>::quiet_NaN());
                stan::math::fill(Sigma,DUMMY_VAR__);
                validate_non_negative_index("Omega", "N2", N2);
                validate_non_negative_index("Omega", "N2", N2);
                matrix_d Omega(static_cast<Eigen::VectorXd::Index>(N2),static_cast<Eigen::VectorXd::Index>(N2));
                (void) Omega;  // dummy to suppress unused var warning

                stan::math::initialize(Omega, std::numeric_limits<double>::quiet_NaN());
                stan::math::fill(Omega,DUMMY_VAR__);
                validate_non_negative_index("K", "N1", N1);
                validate_non_negative_index("K", "N2", N2);
                matrix_d K(static_cast<Eigen::VectorXd::Index>(N1),static_cast<Eigen::VectorXd::Index>(N2));
                (void) K;  // dummy to suppress unused var warning

                stan::math::initialize(K, std::numeric_limits<double>::quiet_NaN());
                stan::math::fill(K,DUMMY_VAR__);
                validate_non_negative_index("K_transpose_div_Sigma", "N2", N2);
                validate_non_negative_index("K_transpose_div_Sigma", "N1", N1);
                matrix_d K_transpose_div_Sigma(static_cast<Eigen::VectorXd::Index>(N2),static_cast<Eigen::VectorXd::Index>(N1));
                (void) K_transpose_div_Sigma;  // dummy to suppress unused var warning

                stan::math::initialize(K_transpose_div_Sigma, std::numeric_limits<double>::quiet_NaN());
                stan::math::fill(K_transpose_div_Sigma,DUMMY_VAR__);
                validate_non_negative_index("Tau", "N2", N2);
                validate_non_negative_index("Tau", "N2", N2);
                matrix_d Tau(static_cast<Eigen::VectorXd::Index>(N2),static_cast<Eigen::VectorXd::Index>(N2));
                (void) Tau;  // dummy to suppress unused var warning

                stan::math::initialize(Tau, std::numeric_limits<double>::quiet_NaN());
                stan::math::fill(Tau,DUMMY_VAR__);


                current_statement_begin__ = 21;
                for (int i = 1; i <= N1; ++i) {
                    current_statement_begin__ = 22;
                    for (int j = 1; j <= N1; ++j) {
                        current_statement_begin__ = 23;
                        stan::math::assign(get_base1_lhs(Sigma,i,j,"Sigma",1), (exp(-(pow((get_base1(x1,i,"x1",1) - get_base1(x1,j,"x1",1)),2))) + if_else(logical_eq(i,j),0.10000000000000001,0.0)));
                    }
                }
                current_statement_begin__ = 25;
                for (int i = 1; i <= N2; ++i) {
                    current_statement_begin__ = 26;
                    for (int j = 1; j <= N2; ++j) {
                        current_statement_begin__ = 27;
                        stan::math::assign(get_base1_lhs(Omega,i,j,"Omega",1), (exp(-(pow((get_base1(x2,i,"x2",1) - get_base1(x2,j,"x2",1)),2))) + if_else(logical_eq(i,j),0.10000000000000001,0.0)));
                    }
                }
                current_statement_begin__ = 29;
                for (int i = 1; i <= N1; ++i) {
                    current_statement_begin__ = 30;
                    for (int j = 1; j <= N2; ++j) {
                        current_statement_begin__ = 31;
                        stan::math::assign(get_base1_lhs(K,i,j,"K",1), exp(-(pow((get_base1(x1,i,"x1",1) - get_base1(x2,j,"x2",1)),2))));
                    }
                }
                current_statement_begin__ = 33;
                stan::math::assign(K_transpose_div_Sigma, mdivide_right(transpose(K),Sigma));
                current_statement_begin__ = 34;
                stan::math::assign(mu, multiply(K_transpose_div_Sigma,y1));
                current_statement_begin__ = 35;
                stan::math::assign(Tau, subtract(Omega,multiply(K_transpose_div_Sigma,K)));
                current_statement_begin__ = 36;
                for (int i = 1; i <= N2; ++i) {
                    current_statement_begin__ = 37;
                    for (int j = (i + 1); j <= N2; ++j) {
                        current_statement_begin__ = 38;
                        stan::math::assign(get_base1_lhs(Tau,i,j,"Tau",1), get_base1(Tau,j,i,"Tau",1));
                    }
                }
                current_statement_begin__ = 40;
                stan::math::assign(L, cholesky_decompose(Tau));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed data

        // validate, set parameter ranges
        num_params_r__ = 0U;
        param_ranges_i__.clear();
        validate_non_negative_index("z", "N2", N2);
        num_params_r__ += N2;
    }

    ~gp_predict_analytic_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("z")))
            throw std::runtime_error("variable z missing");
        vals_r__ = context__.vals_r("z");
        pos__ = 0U;
        validate_non_negative_index("z", "N2", N2);
        context__.validate_dims("initialization", "z", "vector_d", context__.to_vec(N2));
        // generate_declaration z
        vector_d z(static_cast<Eigen::VectorXd::Index>(N2));
        for (int j1__ = 0U; j1__ < N2; ++j1__)
            z(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(z);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable z: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        // model parameters
        stan::io::reader<T__> in__(params_r__,params_i__);

        Eigen::Matrix<T__,Eigen::Dynamic,1>  z;
        (void) z;  // dummy to suppress unused var warning
        if (jacobian__)
            z = in__.vector_constrain(N2,lp__);
        else
            z = in__.vector_constrain(N2);


        // transformed parameters


        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters

        const char* function__ = "validate transformed params";
        (void) function__;  // dummy to suppress unused var warning

        // model body
        try {

            current_statement_begin__ = 47;
            lp_accum__.add(normal_log<propto__>(z, 0, 1));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("z");
        names__.push_back("y2");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(N2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N2);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "gp_predict_analytic_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector_d z = in__.vector_constrain(N2);
        for (int k_0__ = 0; k_0__ < N2; ++k_0__) {
            vars__.push_back(z[k_0__]);
        }

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning



        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters

        // write transformed parameters

        if (!include_gqs__) return;
        // declare and define generated quantities
        validate_non_negative_index("y2", "N2", N2);
        vector_d y2(static_cast<Eigen::VectorXd::Index>(N2));
        (void) y2;  // dummy to suppress unused var warning

        stan::math::initialize(y2, std::numeric_limits<double>::quiet_NaN());
        stan::math::fill(y2,DUMMY_VAR__);


        try {
            current_statement_begin__ = 51;
            stan::math::assign(y2, add(mu,multiply(L,z)));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate generated quantities

        // write generated quantities
        for (int k_0__ = 0; k_0__ < N2; ++k_0__) {
            vars__.push_back(y2[k_0__]);
        }

    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "gp_predict_analytic_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= N2; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "z" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (!include_gqs__) return;
        for (int k_0__ = 1; k_0__ <= N2; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y2" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= N2; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "z" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (!include_gqs__) return;
        for (int k_0__ = 1; k_0__ <= N2; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y2" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
    }

}; // model

}

typedef gp_predict_analytic_model_namespace::gp_predict_analytic_model stan_model;

