
// Code generated by stanc f556d0df
#include <stan/model/model_header.hpp>
namespace dawid_skene_binary_logit_model_namespace {

template <typename T, typename S>
std::vector<T> resize_to_match__(std::vector<T>& dst, const std::vector<S>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, -1>
resize_to_match__(Eigen::Matrix<T, -1, -1>& dst, const Eigen::Matrix<T, -1, -1>& src) {
  dst.resize(src.rows(), src.cols());
  return dst;
}

template <typename T>
Eigen::Matrix<T, 1, -1>
resize_to_match__(Eigen::Matrix<T, 1, -1>& dst, const Eigen::Matrix<T, 1, -1>& src) {
  dst.resize(src.size());
  return dst;
}

template <typename T>
Eigen::Matrix<T, -1, 1>
resize_to_match__(Eigen::Matrix<T, -1, 1>& dst, const Eigen::Matrix<T, -1, 1>& src) {
  dst.resize(src.size());
  return dst;
}
std::vector<double> to_doubles__(std::initializer_list<double> x) {
  return x;
}

std::vector<stan::math::var> to_vars__(std::initializer_list<stan::math::var> x) {
  return x;
}

inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math; 

static int current_statement__ = 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 14, column 2 to column 16)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 15, column 2 to column 28)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 18, column 2 to column 40)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 19, column 2 to column 43)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 20, column 2 to column 16)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 21, column 2 to column 43)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 23, column 4 to column 71)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 24, column 4 to column 71)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 22, column 17 to line 25, column 3)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 22, column 2 to line 25, column 3)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 27, column 4 to column 63)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 26, column 2 to line 27, column 63)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 29, column 2 to column 28)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 30, column 2 to column 36)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 31, column 2 to column 35)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 6, column 2 to column 19)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 7, column 2 to column 19)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 8, column 2 to column 19)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 9, column 2 to column 34)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 10, column 2 to column 34)",
                                                      " (in 'examples/dawid/dawid-skene-binary-logit.stan', line 11, column 2 to column 33)"};



class dawid_skene_binary_logit_model : public model_base_crtp<dawid_skene_binary_logit_model> {

 private:
  int pos__;
  int N;
  int I;
  int J;
  std::vector<int> ii;
  std::vector<int> jj;
  std::vector<int> y;
 
 public:
  ~dawid_skene_binary_logit_model() { }
  
  std::string model_name() const { return "dawid_skene_binary_logit_model"; }
  
  dawid_skene_binary_logit_model(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    typedef double local_scalar_t__;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "dawid_skene_binary_logit_model_namespace::dawid_skene_binary_logit_model";
    (void) function__;  // suppress unused var warning
    
    try {
      
      pos__ = 1;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      
      current_statement__ = 16;
      N = context__.vals_i("N")[(1 - 1)];
      context__.validate_dims("data initialization","I","int",
          context__.to_vec());
      
      current_statement__ = 17;
      I = context__.vals_i("I")[(1 - 1)];
      context__.validate_dims("data initialization","J","int",
          context__.to_vec());
      
      current_statement__ = 18;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 19;
      validate_non_negative_index("ii", "N", N);
      context__.validate_dims("data initialization","ii","int",
          context__.to_vec(N));
      ii = std::vector<int>(N, 0);
      
      current_statement__ = 19;
      assign(ii, nil_index_list(), context__.vals_i("ii"),
        "assigning variable ii");
      current_statement__ = 20;
      validate_non_negative_index("jj", "N", N);
      context__.validate_dims("data initialization","jj","int",
          context__.to_vec(N));
      jj = std::vector<int>(N, 0);
      
      current_statement__ = 20;
      assign(jj, nil_index_list(), context__.vals_i("jj"),
        "assigning variable jj");
      current_statement__ = 21;
      validate_non_negative_index("y", "N", N);
      context__.validate_dims("data initialization","y","int",
          context__.to_vec(N));
      y = std::vector<int>(N, 0);
      
      current_statement__ = 21;
      assign(y, nil_index_list(), context__.vals_i("y"),
        "assigning variable y");
      current_statement__ = 16;
      current_statement__ = 16;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 17;
      current_statement__ = 17;
      check_greater_or_equal(function__, "I", I, 0);
      current_statement__ = 18;
      current_statement__ = 18;
      check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 19;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 19;
        current_statement__ = 19;
        check_greater_or_equal(function__, "ii[sym1__]", ii[(sym1__ - 1)], 1);
      }
      current_statement__ = 19;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 19;
        current_statement__ = 19;
        check_less_or_equal(function__, "ii[sym1__]", ii[(sym1__ - 1)], I);}
      current_statement__ = 20;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 20;
        current_statement__ = 20;
        check_greater_or_equal(function__, "jj[sym1__]", jj[(sym1__ - 1)], 1);
      }
      current_statement__ = 20;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 20;
        current_statement__ = 20;
        check_less_or_equal(function__, "jj[sym1__]", jj[(sym1__ - 1)], J);}
      current_statement__ = 21;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 21;
        current_statement__ = 21;
        check_greater_or_equal(function__, "y[sym1__]", y[(sym1__ - 1)], 0);}
      current_statement__ = 21;
      for (size_t sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 21;
        current_statement__ = 21;
        check_less_or_equal(function__, "y[sym1__]", y[(sym1__ - 1)], 1);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      current_statement__ = 2;
      validate_non_negative_index("logit_alpha", "J", J);
      current_statement__ = 2;
      validate_non_negative_index("logit_alpha", "2", 2);
      num_params_r__ += J * 2;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename T__>
  T__ log_prob(std::vector<T__>& params_r__, std::vector<int>& params_i__,
               std::ostream* pstream__ = 0) const {
    typedef T__ local_scalar_t__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "dawid_skene_binary_logit_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    
    try {
      local_scalar_t__ logit_pi;
      
      current_statement__ = 1;
      logit_pi = in__.scalar();
      current_statement__ = 2;
      validate_non_negative_index("logit_alpha", "J", J);
      current_statement__ = 2;
      validate_non_negative_index("logit_alpha", "2", 2);
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> logit_alpha;
      logit_alpha = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(J, Eigen::Matrix<local_scalar_t__, -1, 1>(2));
      
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= J; ++sym1__) {
        current_statement__ = 2;
        assign(logit_alpha, cons_list(index_uni(sym1__), nil_index_list()),
          in__.vector(2), "assigning variable logit_alpha");}
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= J; ++sym1__) {
        current_statement__ = 2;
        if (jacobian__) {
          current_statement__ = 2;
          assign(logit_alpha, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::ordered_constrain(logit_alpha[(sym1__ - 1)], lp__),
            "assigning variable logit_alpha");
        } else {
          current_statement__ = 2;
          assign(logit_alpha, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::ordered_constrain(logit_alpha[(sym1__ - 1)]),
            "assigning variable logit_alpha");
        }}
      {
        local_scalar_t__ log_pi;
        
        current_statement__ = 3;
        log_pi = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 3;
        log_pi = log_inv_logit(logit_pi);
        local_scalar_t__ log1m_pi;
        
        current_statement__ = 4;
        log1m_pi = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 4;
        log1m_pi = log_inv_logit(-logit_pi);
        local_scalar_t__ zero;
        
        current_statement__ = 5;
        zero = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 5;
        zero = 0;
        current_statement__ = 6;
        validate_non_negative_index("lp", "I", I);
        current_statement__ = 6;
        validate_non_negative_index("lp", "2", 2);
        Eigen::Matrix<local_scalar_t__, -1, -1> lp;
        lp = Eigen::Matrix<local_scalar_t__, -1, -1>(I, 2);
        
        current_statement__ = 6;
        for (size_t sym1__ = 1; sym1__ <= I; ++sym1__) {
          current_statement__ = 6;
          for (size_t sym2__ = 1; sym2__ <= 2; ++sym2__) {
            current_statement__ = 6;
            assign(lp,
              cons_list(index_uni(sym1__),
                cons_list(index_uni(sym2__), nil_index_list())),
              std::numeric_limits<double>::quiet_NaN(),
              "assigning variable lp");}}
        current_statement__ = 6;
        assign(lp, nil_index_list(), rep_matrix(zero, I, 2),
          "assigning variable lp");
        current_statement__ = 10;
        for (size_t n = 1; n <= N; ++n) {
          current_statement__ = 7;
          assign(lp,
            cons_list(index_uni(ii[(n - 1)]),
              cons_list(index_uni(1), nil_index_list())),
            (rvalue(lp,
               cons_list(index_uni(ii[(n - 1)]),
                 cons_list(index_uni(1), nil_index_list())), "lp") +
              bernoulli_logit_lpmf<false>(y[(n - 1)],
                logit_alpha[(jj[(n - 1)] - 1)][(2 - 1)])),
            "assigning variable lp");
          current_statement__ = 8;
          assign(lp,
            cons_list(index_uni(ii[(n - 1)]),
              cons_list(index_uni(2), nil_index_list())),
            (rvalue(lp,
               cons_list(index_uni(ii[(n - 1)]),
                 cons_list(index_uni(2), nil_index_list())), "lp") +
              bernoulli_logit_lpmf<false>(y[(n - 1)],
                logit_alpha[(jj[(n - 1)] - 1)][(1 - 1)])),
            "assigning variable lp");}
        current_statement__ = 12;
        for (size_t i = 1; i <= I; ++i) {
          current_statement__ = 11;
          lp_accum__.add(
            log_mix(inv_logit(logit_pi),
              rvalue(lp,
                cons_list(index_uni(i),
                  cons_list(index_uni(1), nil_index_list())), "lp"),
              rvalue(lp,
                cons_list(index_uni(i),
                  cons_list(index_uni(2), nil_index_list())), "lp")));}
        current_statement__ = 13;
        lp_accum__.add(normal_log<propto__>(logit_pi, 0, 1.8));
        current_statement__ = 14;
        lp_accum__.add(
          normal_log<propto__>(
            rvalue(logit_alpha,
              cons_list(index_omni(),
                cons_list(index_uni(1), nil_index_list())), "logit_alpha"),
            -1, 2));
        current_statement__ = 15;
        lp_accum__.add(
          normal_log<propto__>(
            rvalue(logit_alpha,
              cons_list(index_omni(),
                cons_list(index_uni(2), nil_index_list())), "logit_alpha"),
            1, 2));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob() 
    
  template <typename RNG>
  void write_array(RNG& base_rng__, std::vector<double>& params_r__,
                   std::vector<int>& params_i__, std::vector<double>& vars__,
                   bool emit_transformed_parameters__ = true,
                   bool emit_generated_quantities__ = true,
                   std::ostream* pstream__ = 0) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "dawid_skene_binary_logit_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    
    try {
      double logit_pi;
      
      current_statement__ = 1;
      logit_pi = in__.scalar();
      current_statement__ = 2;
      validate_non_negative_index("logit_alpha", "J", J);
      current_statement__ = 2;
      validate_non_negative_index("logit_alpha", "2", 2);
      std::vector<Eigen::Matrix<double, -1, 1>> logit_alpha;
      logit_alpha = std::vector<Eigen::Matrix<double, -1, 1>>(J, Eigen::Matrix<double, -1, 1>(2));
      
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= J; ++sym1__) {
        current_statement__ = 2;
        assign(logit_alpha, cons_list(index_uni(sym1__), nil_index_list()),
          in__.vector(2), "assigning variable logit_alpha");}
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= J; ++sym1__) {
        current_statement__ = 2;
        assign(logit_alpha, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::ordered_constrain(logit_alpha[(sym1__ - 1)]),
          "assigning variable logit_alpha");}
      vars__.push_back(logit_pi);
      for (size_t sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (size_t sym2__ = 1; sym2__ <= J; ++sym2__) {
          vars__.push_back(logit_alpha[(sym2__ - 1)][(sym1__ - 1)]);}}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array() 
    
  void transform_inits(const stan::io::var_context& context__,
                       std::vector<int>& params_i__,
                       std::vector<double>& vars__, std::ostream* pstream__) const {
    typedef double local_scalar_t__;
    vars__.resize(0);
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      
      pos__ = 1;
      double logit_pi;
      
      current_statement__ = 1;
      logit_pi = context__.vals_r("logit_pi")[(1 - 1)];
      current_statement__ = 2;
      validate_non_negative_index("logit_alpha", "J", J);
      current_statement__ = 2;
      validate_non_negative_index("logit_alpha", "2", 2);
      std::vector<Eigen::Matrix<double, -1, 1>> logit_alpha;
      logit_alpha = std::vector<Eigen::Matrix<double, -1, 1>>(J, Eigen::Matrix<double, -1, 1>(2));
      
      {
        std::vector<local_scalar_t__> logit_alpha_flat__;
        current_statement__ = 2;
        assign(logit_alpha_flat__, nil_index_list(),
          context__.vals_r("logit_alpha"),
          "assigning variable logit_alpha_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (size_t sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 2;
          for (size_t sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 2;
            assign(logit_alpha,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              logit_alpha_flat__[(pos__ - 1)],
              "assigning variable logit_alpha");
            current_statement__ = 2;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 2;
      for (size_t sym1__ = 1; sym1__ <= J; ++sym1__) {
        current_statement__ = 2;
        assign(logit_alpha, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::ordered_free(logit_alpha[(sym1__ - 1)]),
          "assigning variable logit_alpha");}
      vars__.push_back(logit_pi);
      for (size_t sym1__ = 1; sym1__ <= 2; ++sym1__) {
        for (size_t sym2__ = 1; sym2__ <= J; ++sym2__) {
          vars__.push_back(logit_alpha[(sym2__ - 1)][(sym1__ - 1)]);}}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits() 
    
  void get_param_names(std::vector<std::string>& names__) const {
    
    names__.resize(0);
    names__.push_back("logit_pi");
    names__.push_back("logit_alpha");
    } // get_param_names() 
    
  void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.resize(0);
    std::vector<size_t> dims__;
    dimss__.push_back(dims__);
    dims__.resize(0);
    dims__.push_back(J);
    
    dims__.push_back(2);
    dimss__.push_back(dims__);
    dims__.resize(0);
    
    } // get_dims() 
    
  void constrained_param_names(std::vector<std::string>& param_names__,
                               bool emit_transformed_parameters__ = true,
                               bool emit_generated_quantities__ = true) const {
    
    param_names__.push_back(std::string() + "logit_pi");
    for (size_t sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        for (size_t sym2__ = 1; sym2__ <= J; ++sym2__) {
          {
            param_names__.push_back(std::string() + "logit_alpha" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  void unconstrained_param_names(std::vector<std::string>& param_names__,
                                 bool emit_transformed_parameters__ = true,
                                 bool emit_generated_quantities__ = true) const {
    
    param_names__.push_back(std::string() + "logit_pi");
    for (size_t sym1__ = 1; sym1__ <= 2; ++sym1__) {
      {
        for (size_t sym2__ = 1; sym2__ <= J; ++sym2__) {
          {
            param_names__.push_back(std::string() + "logit_alpha" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"logit_pi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"logit_alpha\",\"type\":{\"name\":\"array\",\"length\":" << J << ",\"element_type\":{\"name\":\"vector\",\"length\":" << 2 << "}},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"logit_pi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"logit_alpha\",\"type\":{\"name\":\"array\",\"length\":" << J << ",\"element_type\":{\"name\":\"vector\",\"length\":" << 2 << "}},\"block\":\"parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool emit_transformed_parameters__ = true,
                     bool emit_generated_quantities__ = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng__, params_r_vec, params_i_vec, vars_vec,
          emit_transformed_parameters__, emit_generated_quantities__, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    template <bool propto__, bool jacobian__, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }

};
}

typedef dawid_skene_binary_logit_model_namespace::dawid_skene_binary_logit_model stan_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


