
// Code generated by stanc 22b4f754
#include <stan/model/model_header.hpp>
namespace diamonds_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 29> locations_array__ = 
{" (found before start of program)",
 " (in 'examples/diamonds/diamonds.stan', line 20, column 2 to column 15)",
 " (in 'examples/diamonds/diamonds.stan', line 22, column 2 to column 17)",
 " (in 'examples/diamonds/diamonds.stan', line 23, column 2 to column 22)",
 " (in 'examples/diamonds/diamonds.stan', line 27, column 2 to column 34)",
 " (in 'examples/diamonds/diamonds.stan', line 28, column 2 to column 49)",
 " (in 'examples/diamonds/diamonds.stan', line 29, column 2 to line 30, column 40)",
 " (in 'examples/diamonds/diamonds.stan', line 33, column 4 to column 51)",
 " (in 'examples/diamonds/diamonds.stan', line 32, column 19 to line 34, column 3)",
 " (in 'examples/diamonds/diamonds.stan', line 32, column 2 to line 34, column 3)",
 " (in 'examples/diamonds/diamonds.stan', line 4, column 2 to column 17)",
 " (in 'examples/diamonds/diamonds.stan', line 5, column 9 to column 10)",
 " (in 'examples/diamonds/diamonds.stan', line 5, column 2 to column 14)",
 " (in 'examples/diamonds/diamonds.stan', line 6, column 2 to column 17)",
 " (in 'examples/diamonds/diamonds.stan', line 7, column 9 to column 10)",
 " (in 'examples/diamonds/diamonds.stan', line 7, column 12 to column 13)",
 " (in 'examples/diamonds/diamonds.stan', line 7, column 2 to column 17)",
 " (in 'examples/diamonds/diamonds.stan', line 8, column 2 to column 17)",
 " (in 'examples/diamonds/diamonds.stan', line 11, column 2 to column 17)",
 " (in 'examples/diamonds/diamonds.stan', line 12, column 9 to column 10)",
 " (in 'examples/diamonds/diamonds.stan', line 12, column 12 to column 14)",
 " (in 'examples/diamonds/diamonds.stan', line 12, column 2 to column 19)",
 " (in 'examples/diamonds/diamonds.stan', line 13, column 9 to column 11)",
 " (in 'examples/diamonds/diamonds.stan', line 13, column 2 to column 21)",
 " (in 'examples/diamonds/diamonds.stan', line 15, column 4 to column 34)",
 " (in 'examples/diamonds/diamonds.stan', line 16, column 4 to column 42)",
 " (in 'examples/diamonds/diamonds.stan', line 14, column 17 to line 17, column 3)",
 " (in 'examples/diamonds/diamonds.stan', line 14, column 2 to line 17, column 3)",
 " (in 'examples/diamonds/diamonds.stan', line 20, column 9 to column 11)"};



class diamonds_model final : public model_base_crtp<diamonds_model> {

 private:
  int N;
  Eigen::Matrix<double, -1, 1> Y__;
  int K;
  Eigen::Matrix<double, -1, -1> X__;
  int prior_only;
  int Kc;
  Eigen::Matrix<double, -1, -1> Xc__;
  Eigen::Matrix<double, -1, 1> means_X__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> Y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> Xc{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> means_X{nullptr, 0};
 
 public:
  ~diamonds_model() { }
  
  inline std::string model_name() const final { return "diamonds_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 22b4f754", "stancflags = "};
  }
  
  
  diamonds_model(stan::io::var_context& context__,
                 unsigned int random_seed__ = 0,
                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "diamonds_model_namespace::diamonds_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 10;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 10;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 10;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 11;
      validate_non_negative_index("Y", "N", N);
      current_statement__ = 12;
      context__.validate_dims("data initialization","Y","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      Y__ = Eigen::Matrix<double, -1, 1>(N);
      new (&Y) Eigen::Map<Eigen::Matrix<double, -1, 1>>(Y__.data(), N);
      
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 12;
        Y_flat__ = context__.vals_r("Y");
        current_statement__ = 12;
        pos__ = 1;
        current_statement__ = 12;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 12;
          assign(Y, Y_flat__[(pos__ - 1)],
            "assigning variable Y", index_uni(sym1__));
          current_statement__ = 12;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 13;
      context__.validate_dims("data initialization","K","int",
           std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 13;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 13;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 14;
      validate_non_negative_index("X", "N", N);
      current_statement__ = 15;
      validate_non_negative_index("X", "K", K);
      current_statement__ = 16;
      context__.validate_dims("data initialization","X","double",
           std::vector<size_t>{static_cast<size_t>(N),
            static_cast<size_t>(K)});
      X__ = Eigen::Matrix<double, -1, -1>(N, K);
      new (&X) Eigen::Map<Eigen::Matrix<double, -1, -1>>(X__.data(), N, K);
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 16;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 16;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 16;
            assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", index_uni(sym2__), index_uni(sym1__));
            current_statement__ = 16;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 17;
      context__.validate_dims("data initialization","prior_only","int",
           std::vector<size_t>{});
      prior_only = std::numeric_limits<int>::min();
      
      current_statement__ = 17;
      prior_only = context__.vals_i("prior_only")[(1 - 1)];
      current_statement__ = 18;
      Kc = std::numeric_limits<int>::min();
      
      current_statement__ = 18;
      Kc = (K - 1);
      current_statement__ = 19;
      validate_non_negative_index("Xc", "N", N);
      current_statement__ = 20;
      validate_non_negative_index("Xc", "Kc", Kc);
      current_statement__ = 21;
      Xc__ = Eigen::Matrix<double, -1, -1>(N, Kc);
      new (&Xc) Eigen::Map<Eigen::Matrix<double, -1, -1>>(Xc__.data(), N, Kc);
      stan::math::fill(Xc, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 22;
      validate_non_negative_index("means_X", "Kc", Kc);
      current_statement__ = 23;
      means_X__ = Eigen::Matrix<double, -1, 1>(Kc);
      new (&means_X) Eigen::Map<Eigen::Matrix<double, -1, 1>>(means_X__.data(), Kc);
      stan::math::fill(means_X, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 27;
      for (int i = 2; i <= K; ++i) {
        current_statement__ = 24;
        assign(means_X, mean(rvalue(X, "X", index_omni(), index_uni(i))),
          "assigning variable means_X", index_uni((i - 1)));
        current_statement__ = 25;
        assign(Xc,
          subtract(rvalue(X, "X", index_omni(), index_uni(i)),
            rvalue(means_X, "means_X", index_uni((i - 1)))),
          "assigning variable Xc", index_omni(), index_uni((i - 1)));
      }
      current_statement__ = 28;
      validate_non_negative_index("b", "Kc", Kc);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = Kc + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "diamonds_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> b;
      b = Eigen::Matrix<local_scalar_t__, -1, 1>(Kc);
      stan::math::fill(b, DUMMY_VAR__);
      
      current_statement__ = 1;
      b = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(Kc);
      local_scalar_t__ Intercept;
      Intercept = DUMMY_VAR__;
      
      current_statement__ = 2;
      Intercept = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      current_statement__ = 3;
      sigma = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      {
        current_statement__ = 4;
        lp_accum__.add(normal_lpdf<false>(b, 0, 1));
        current_statement__ = 5;
        lp_accum__.add(student_t_lpdf<false>(Intercept, 3, 8, 10));
        current_statement__ = 6;
        lp_accum__.add(
          (student_t_lpdf<false>(sigma, 3, 0, 10) -
            (1 * student_t_lccdf(0, 3, 0, 10))));
        current_statement__ = 9;
        if (logical_negation(prior_only)) {
          current_statement__ = 7;
          lp_accum__.add(
            normal_lpdf<propto__>(Y, add(Intercept, multiply(Xc, b)), sigma));
        } 
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "diamonds_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> b;
      b = Eigen::Matrix<double, -1, 1>(Kc);
      stan::math::fill(b, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      b = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(Kc);
      double Intercept;
      Intercept = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      Intercept = in__.template read<local_scalar_t__>();
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      for (int sym1__ = 1; sym1__ <= Kc; ++sym1__) {
        vars__.emplace_back(b[(sym1__ - 1)]);
      }
      vars__.emplace_back(Intercept);
      vars__.emplace_back(sigma);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    int current_statement__ = 0; 
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> b;
      b = Eigen::Matrix<double, -1, 1>(Kc);
      stan::math::fill(b, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> b_flat__;
        current_statement__ = 1;
        b_flat__ = context__.vals_r("b");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= Kc; ++sym1__) {
          current_statement__ = 1;
          assign(b, b_flat__[(pos__ - 1)],
            "assigning variable b", index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      double Intercept;
      Intercept = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      Intercept = context__.vals_r("Intercept")[(1 - 1)];
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      double sigma_free__;
      sigma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_free__ = stan::math::lb_free(sigma, 0);
      for (int sym1__ = 1; sym1__ <= Kc; ++sym1__) {
        vars__.emplace_back(b[(sym1__ - 1)]);
      }
      vars__.emplace_back(Intercept);
      vars__.emplace_back(sigma_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"b", "Intercept", "sigma"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(Kc)
                                                                   },
      std::vector<size_t>{}, std::vector<size_t>{}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= Kc; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "b" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "Intercept");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= Kc; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "b" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "Intercept");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Kc) + "},\"block\":\"parameters\"},{\"name\":\"Intercept\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"b\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(Kc) + "},\"block\":\"parameters\"},{\"name\":\"Intercept\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec;
      vars_vec.reserve(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars,
       emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec;
      params_r_vec.reserve(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }

};
}
using stan_model = diamonds_model_namespace::diamonds_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return diamonds_model_namespace::profiles__;
}

#endif


