name: Manual build test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop, test ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:  
        submodules: 'recursive'
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Download & install RTools
      run: |
        Invoke-WebRequest -Uri https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe -OutFile ./R35.exe
        Start-Process -FilePath ./R35.exe -ArgumentList /VERYSILENT -NoNewWindow -Wait
        echo "::add-path::C:/Rtools/bin"
        echo "::add-path::C:/Rtools/mingw_64/bin"
      shell: powershell
    - name: Print toolchain versions and paths
      run: |
        g++ --version
        mingw32-make --version
        Get-Command g++ | Select-Object -ExpandProperty Definition
        Get-Command mingw32-make | Select-Object -ExpandProperty Definition
      shell: powershell
    - name: Build Math libs & add to PATH
      run: |
        mingw32-make -f stan/lib/stan_math/make/standalone math-libs
        echo "::add-path::D:/a/cmdstan/cmdstan/stan/lib/stan_math/lib/tbb"
      shell: powershell
    - name: Compile & run the example model
      run: |
        mingw32-make examples/bernoulli/bernoulli.exe
        ./examples/bernoulli/bernoulli.exe sample data file=examples/bernoulli/bernoulli.data.json
      shell: powershell
